# Cache Redis configuration
redis:
    url: '%env(REDIS_URL)%'
    default_ttl: 3600
    
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://localhost:6379
        pools:
            translation_cache:
                adapter: cache.adapter.redis
                default_lifetime: 86400 # 24 hours
                provider: 'redis://localhost:6379'
            
            product_cache:
                adapter: cache.adapter.redis  
                default_lifetime: 3600 # 1 hour
                provider: 'redis://localhost:6379'
                
            category_cache:
                adapter: cache.adapter.redis
                default_lifetime: 7200 # 2 hours  
                provider: 'redis://localhost:6379'