doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # Configure your default database connection here
                driver: 'pdo_mysql'
        
        types:
            # Add any custom types here
    
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        
        # Query cache configuration for better performance
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool
        
        metadata_cache_driver:
            type: pool
            pool: doctrine.metadata_cache_pool