framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAIL_FROM_ADDRESS)%'
        headers:
            from: '%env(MAIL_FROM_NAME)% <%env(MAIL_FROM_ADDRESS)%>'