ecommerce_frontend:
    resource: '../src/Bundle/EcommerceBundle/Controller/Frontend'
    type: annotation
    prefix: /shop

ecommerce_admin:
    resource: '../src/Bundle/EcommerceBundle/Controller/Admin'
    type: annotation
    prefix: /admin/ecommerce