nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
            '^/embed/.*': SAMEORIGIN

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    # Content Security Policy
    csp:
        enabled: true
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive: false
            default-src: "'self'"
            script-src: "'self' 'unsafe-inline' 'unsafe-eval'"
            style-src: "'self' 'unsafe-inline'"
            img-src: "'self' data: https:"
            font-src: "'self' data:"
            connect-src: "'self'"
            frame-src: "'none'"
            object-src: "'none'"
            media-src: "'self'"
            child-src: "'none'"
            form-action: "'self'"
            frame-ancestors: "'none'"
            base-uri: "'self'"

    # HTTP Strict Transport Security
    forced_ssl:
        enabled: true
        hsts_max_age: 31536000
        hsts_subdomains: true
        hsts_preload: true

    # External redirects
    external_redirects:
        abort: true
        log: true

    # Flexible SSL
    flexible_ssl:
        enabled: true
